---
- name: Metricbeat playbook
  hosts: webservers
  become: true
  tasks:
  # name: cleanup
  - command: apt remove --purge -y metricbeat
  # command: rm /etc/metricbeat/metricbeat.yml
  - name: download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb
  - name: install metric beat
    command: dpkg -i metricbeat-7.4.0-amd64.deb
  - name: copy metricbeat config file
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Run metricbeat modules enable docker
    command: metricbeat modules enable docker
  - name: Run metricbeat setup
    command: metricbeat setup
  - name: Run service metricbeat start
    command: service metricbeat start

  - name: enable metricbeat
    systemd:
      name: metricbeat
      enabled: yes
 
